#sdk: "/usr/local/lib/ruby/gems/1.9.1/gems/rhodes-3.3.3"
sdkversion: 3.3.3
name: catav
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.catav
  BundleURLScheme: catav
wp:
  productid: '7f9cd800-c146-012f-9c4a-3860775fb903'
symbian:
  uid: '0xe2c5561a'
android:
  version: 4.0.3

extensions: ["json", "another-extension"]
